# Ścieżki do plików
paths:
  nrg_pattern: "data/USA_segmentation/NRG_images/*.png"
  rgb_pattern: "data/USA_segmentation/RGB_images/*.png"
  masks_pattern: "data/USA_segmentation/masks/*.png"
  output_dir: "./generated_masks"

# Parametry detekcji
detection:
  ndvi_percentile: 35
  min_object_size: 50
  morph_kernel_size: [3, 3]

# Progi kolorów HSV dla lasu (Lower i Upper)
forest_hsv:
  lower: [0.65, 0.15, 0.25]
  upper: [0.90, 1.00, 1.00]

# Ustawienia eksperymentu
experiment:
  num_samples: 5